# Generated by Django 5.2.5 on 2025-08-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='guide',
            field=models.TextField(blank=True),
        ),
    ]
